ALTER TABLE public.listings ALTER COLUMN user_id DROP NOT NULL;

INSERT INTO public.listings (user_id, listing_type, title, description, about_master, is_free, price, start_date, end_date, category, subcategory, city, map_location)
VALUES
  (NULL, 'physical', 'Tabla Foundations — 6 week gharana course', 'Weekly hands-on sessions covering theka, kaida and basic compositions for absolute beginners.', 'Pt. Ravi Deshpande, 22 years of Farukhabad gharana training and stage performance.', false, 1800, current_date + 5, current_date + 47, 'music', 'Tabla', 'Bangalore', 'https://maps.google.com/?q=Indiranagar+Bangalore'),
  (NULL, 'online', 'Kannada for beginners — speak in 4 weeks', 'Live online sessions focused on everyday spoken Kannada, script basics and common phrases.', 'S. Ananda Rao, language coach with 12 years of teaching experience.', false, 999, current_date + 3, current_date + 31, 'language', 'Kannada', NULL, NULL),
  (NULL, 'competition', 'Rasika Utsav — Carnatic vocal open mic', 'Open stage competition for young vocalists, with prizes across three age groups.', 'Hosted by Kalasutra Bhavan, a 30-year-old cultural trust.', false, 500, current_date + 14, current_date + 14, 'music', 'Vocal — Carnatic', 'Bangalore', 'https://maps.google.com/?q=Jayanagar+Bangalore'),
  (NULL, 'online', 'Live options desk — weekly strategy clinic', 'A free weekly clinic breaking down real market setups, risk sizing and trade journaling.', 'Meera Nair, full-time derivatives trader and mentor.', true, 0, current_date + 2, current_date + 60, 'trading', 'Options', NULL, NULL),
  (NULL, 'online', 'Practical AI workflows for small teams', 'Build repeatable prompt workflows, automations and review checklists for daily work.', 'Devika Iyer, product lead and AI workflow consultant.', false, 2400, current_date + 9, current_date + 16, 'ai_tools', 'Automation', NULL, NULL),
  (NULL, 'physical', 'Bansuri flute for beginners', 'Breath control, fingering and first ragas in a small in-person batch.', 'Guru Shyam Prasad, disciple of the Maihar tradition.', true, 0, current_date + 7, current_date + 35, 'music', 'Flute', 'Bangalore', 'https://maps.google.com/?q=Malleshwaram+Bangalore');